
services:
  - type: web
    name: muzak-lab-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    redirects:
      - source: /.*
        destination: /index.html
        status: 200
